# Generated by Django 3.1.2 on 2021-02-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210129_0803'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='shop_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.shopproduct', verbose_name='Shop product'),
        ),
    ]
