# Generated by Django 3.1.2 on 2021-02-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210204_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Price'),
        ),
    ]
