# Generated by Django 3.1.2 on 2021-01-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Sub title')),
                ('image', models.ImageField(upload_to='siteview/slide_show/images', verbose_name='Background image')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('action_text', models.CharField(max_length=50, verbose_name='Action text')),
                ('action_url', models.URLField(verbose_name='Action url')),
            ],
        ),
    ]
