# Generated by Django 3.1.2 on 2021-01-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_like'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Sub title')),
                ('image', models.ImageField(upload_to='siteview/best_brands/images', verbose_name='Background image')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('action_text', models.CharField(max_length=50, verbose_name='Action text')),
                ('action_url', models.URLField(verbose_name='Action url')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_brand', related_query_name='best_brand', to='store.brand', verbose_name='brand')),
            ],
        ),
    ]
