# Generated by Django 3.1.2 on 2021-01-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_like'),
        ('homepage', '0002_bestbrands'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestBrands',
            new_name='BestBrand',
        ),
    ]
