# Generated by Django 3.1.2 on 2021-01-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210109_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestbrand',
            name='action_text',
        ),
        migrations.RemoveField(
            model_name='bestbrand',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='bestbrand',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bestbrand',
            name='subtitle',
        ),
    ]
