# Generated by Django 3.1.2 on 2021-01-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_like'),
        ('homepage', '0004_auto_20210116_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionalDiscounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(verbose_name='discount')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_product', related_query_name='discount_product', to='store.shopproduct', verbose_name='product')),
            ],
        ),
    ]
