# Generated by Django 3.1.2 on 2021-01-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_exceptionaldiscounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionaldiscounts',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount'),
        ),
    ]
