# Generated by Django 3.1.2 on 2021-01-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20210117_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionaldiscounts',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='discount'),
        ),
    ]
