# Generated by Django 3.1.2 on 2021-01-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20210117_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionaldiscounts',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=100, verbose_name='discount'),
        ),
    ]
