# Generated by Django 3.1.2 on 2021-02-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210209_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='condition',
        ),
        migrations.AddField(
            model_name='like',
            name='product_scores',
            field=models.IntegerField(default=0, verbose_name='product_scores'),
        ),
    ]
