# Generated by Django 3.1.2 on 2021-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210209_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='product_scores',
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=True, verbose_name='Condition'),
        ),
    ]
