# Generated by Django 3.1.2 on 2021-02-26 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_auto_20210218_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'ordering': ['price'], 'verbose_name': 'shop_product', 'verbose_name_plural': 'shop_products'},
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', related_query_name='user_like', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
